### ISSUE TITLE
Cstep bevel reset. 

### ISSUE THREAD

**Issue by mx1001** [mx1001/HOps#59]
Now I see the bevel is resetting to .2 instead of keeping the same. This would also be a good oportunity to experiment with a decrementing toggle system 
so that you can check a box and if you do it will decrecment the bevel by half with each cstep. This would work pretty well in rare cases whrre you want to automatically step down.

But the way it is now it resets to .02

http://i.imgur.com/43x9bFj.gifv

**Comment by niewinny** [comment]
I am 99% sure that it worked the same before, this is because cstep apply bevel, and then is using csharpen, so since there is no bevel modifier the new one is created and 0,02 is our standard value for new one

That is not affecting applied bevel on any way.

**Comment by mx1001** [comment]
okay fine. Im just being paranoid. But why cant it keep the old value? And
then we can play with it?

**Comment by niewinny** [comment]
Because that value refer to new bevel, the one that will show after you
press sstep, it  is not related to cstep anymore

We don't actually know the value yet this is why it is set to 0,02 it is
the starting value. If that make sense.

śr., 3 lut 2016, 04:36 mx1001 użytkownik <notifications@github.com> napisał:

**Comment by niewinny** [comment]
are we ok with that behavior t the end ? I did play a lot with sstep yesterday and it works just fine, should I still look at it ?
